## Goneovim settings.toml
## All of the following commented configuration items have default values.

## Copy to %userprofile%.config\goneovim\settings.toml
## For more info check: https://github.com/akiyosi/goneovim/wiki/Usage#configuration

[Editor]
## If enabled, when the Close button of the application window is clicked,
## the application will exit without confirmation, even if there are unsaved
## updates.
IgnoreSaveConfirmationWithCloseButton = false

## This option makes the whole GUI window in semi-transparent.
## This setting also implicitly enables the Drawborder setting
# Transparent = 0.5

## Launch goneovim with full screen window size.
StartFullscreen = true

## Enable the ability to remember the last window geometry that was displayed
## and restore it at the next startup.
RestoreWindowGeometry = false
## This option allows you to hide the mouse cursor in the gooneovim window
## when you type a key, and to redisplay it when you move the mouse cursor again.
HideMouseWhenTyping = true

## Animates the scrolling behavior of Neovim when the scroll command is entered.
SmoothScroll = true
## Specifies the speed of animation in smooth scrolling.
SmoothScrollDuration = 300
## Disables horizontal scrolling for smooth scrolling with the touchpad.
# DisableHorizontalScroll = true

[Workspace]
## This setting sets the format of the path string of CWD in the sidebar.
##  name: directoryname
##  full: /path/to/directoryname
##  minimum: /p/t/directoryname
# PathStyle = "minimum"

## Specifies whether the last exited session should be restored at the next startup.
RestoreSession = true
